#! /bin/sh
# /etc/init.d/kafka: start the kafka daemon.

# chkconfig: 345 80 20
# description: kafka

HOME=/opt/kafka_2.11-0.9.0.0
USER=root

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

prog=kafka
DESC="kafka daemon"

RETVAL=0

# detect the distribution:
if [ -f /etc/redhat-release -o -f /etc/fedora-release ] ; then
  DISTRIBUTION="redhat"
elif [ -f /etc/SuSE-release ] ; then
  DISTRIBUTION="suse"
elif [ -f /etc/debian_version ] ; then
  DISTRIBUTION="debian"
else
  DISTRIBUTION="debian"
fi

# Source function library.
[ "$DISTRIBUTION" = "redhat" ] && . /etc/init.d/functions
[ "$DISTRIBUTION" = "suse" ] && . /etc/rc.status

if [ "$DISTRIBUTION" = "suse" ] ; then
  echo_success() {
    rc_status -v
  }
  echo_failure() {
    rc_status -v
  }
  success() {
    echo_success
  }
  failure() {
    echo_success
  }
elif [ "$DISTRIBUTION" = "debian" ] ; then
  echo_success() {
    echo ok
  }
  echo_failure() {
    echo failed
  }
  success() {
    echo_success
  }
  failure() {
    echo_success
  }
fi

start() {
  ulimit -n 65536
  ulimit -s 10240
  ulimit -c unlimited
  echo -n $"Starting $prog: "
  cd $HOME
  nohup su $USER -c "./bin/kafka-server-start.sh ./config/server.properties </dev/null 2>&1 | cronolog ./log/kafka/kafka.%Y%m%d.log 2>&1" </dev/null >/dev/null 2>&1 &
  RETVAL=$?
  [ $RETVAL -eq 0 ] && echo_success
  [ $RETVAL -ne 0 ] && echo_failure
    echo
  return $RETVAL
}

stop() {
  echo $"Stopping $prog: "
  cd $HOME
  su $USER -c "./bin/kafka-server-stop.sh"
  [ $RETVAL -eq 0 ] && echo_success
  [ $RETVAL -ne 0 ] && echo_failure
    echo
  return $RETVAL
}

reload() {
  stop
  start
}

restart() {
  stop
  start
}

case "$1" in
start)
  start
  ;;

stop)
  stop
  ;;

reload)
  reload
  ;;

restart)
  restart
  ;;

*)
  echo $"Usage: $0 {start|stop|reload|restart}"
  exit 1
esac

exit $?

